# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Add to path
homebin="$HOME/.local/bin"
case ":$PATH:" in
  *":$homebin:"*) :;; # already there
  *) PATH="$homebin:$PATH";; # or PATH="$PATH:$homebin"
esac

# User specific aliases and functions
alias vi=vim
alias l="ls -lah"
alias c="clear"
alias t="tmux"
alias 'cleandocker'='docker stop `docker ps -q`; docker container rm `docker ps -aq`; docker image rm `docker image ls -q`'
alias cleanssh='rm ~/.ssh/known_hosts'

function exitcode {
        code=$?
        if [[ $code != 0 ]]
        then
                echo -n "[$code]"
        fi
}

# Commandline
export PS1="\u@\h:\w\$(exitcode)\$ \[$(tput sgr0)\]"

# Sudoedit editor
export SUDO_EDITOR=vim

# For i3
export TERMINAL=terminator
export EDITOR=vim
